version: '3.9'

services:
  wordpress:
    image: wordpress:php7.1-apache
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
    links:
      - mysql:mysql
    volumes:
      # - ~/docker/wordpress/wp-content:/var/www/html/wp-content #esto lo crea en la carpeta de usuario
      - ./Volumenes/wordpress/wp-content:/var/www/html/wp-content

  mysql:
    image: mariadb:10.6.13
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # - ~/docker/mysql-data:/var/lib/mysql # esto genera una carpeta Docker en la carpeta de usuario
      - ./Volumenes/mysql-data:/var/lib/mysql 
#esto con el punto crea una carpeta volumenes, no puedes crear en D:/ una carpeta de volumenes
#ejecuta con podman-compose -f docker-compose.yml up -d